services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - packages/server/.env
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:7
    command: mongod --quiet
    volumes:
      - mongo_data:/data/db
    env_file:
      - packages/server/.env

  postgres:
    image: postgres:16-alpine
    # environment:
    #   - POSTGRES_DB=eventhub
    #   - POSTGRES_USER=admin
    #   - POSTGRES_PASSWORD=password123
    env_file:
      - packages/server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass password123
    env_file:
      - packages/server/.env
      
volumes:
  mongo_data:
  postgres_data:
