services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - packages/server/.env
    restart: unless-stopped
    depends_on:
      - mongo
      - postgres
      - redis
    networks:
      - eventhub-network

  mongo:
    image: mongo:7
    command: mongod --quiet
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    env_file:
      - packages/server/.env
    networks:
      - eventhub-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=eventhub
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    env_file:
      - packages/server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventhub-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass password123
    restart: unless-stopped
    env_file:
      - packages/server/.env
    networks:
      - eventhub-network

  frontend:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://server:8000
    depends_on:
      - server
    networks:
      - eventhub-network
      
volumes:
  mongo_data:
  postgres_data:

networks:
  eventhub-network:
    driver: bridge