name: CI Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Insallation de pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Installation des dépendances
      - name: Install dependencies
        run: pnpm install

      # Build du projet
      - name: Build
        run: pnpm build
